---
- hosts: web
  become: yes
  tasks:
    - name: Update YUM packages
      yum:
        name: '*'
        state: latest

    - name: Install Python3 and pip
      yum:
        name: ['python3', 'python3-pip']
        state: present

    - name: Install Flask and Gunicorn
      pip:
        name:
          - flask
          - gunicorn
        executable: pip3

    - name: Copy Flask app
      copy:
        src: ../app.py
        dest: /home/ec2-user/app.py
        owner: ec2-user
        group: ec2-user

    - name: Setup Gunicorn systemd service
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn daemon
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user
          ExecStart=/usr/bin/gunicorn -w 3 -b 127.0.0.1:5000 app:app

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: started

    - name: Enable Nginx using amazon-linux-extras
      shell: amazon-linux-extras enable nginx1

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Copy Nginx config
      copy:
        src: ../nginx/flask_dashboard.conf
        dest: /etc/nginx/conf.d/flask_dashboard.conf

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
